// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: pkg/rpc/octopos.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cluster_RegisterNode_FullMethodName         = "/octopos.rpc.Cluster/RegisterNode"
	Cluster_Heartbeat_FullMethodName            = "/octopos.rpc.Cluster/Heartbeat"
	Cluster_GetClusterState_FullMethodName      = "/octopos.rpc.Cluster/GetClusterState"
	Cluster_Execute_FullMethodName              = "/octopos.rpc.Cluster/Execute"
	Cluster_Signal_FullMethodName               = "/octopos.rpc.Cluster/Signal"
	Cluster_Wait_FullMethodName                 = "/octopos.rpc.Cluster/Wait"
	Cluster_GetJobStatus_FullMethodName         = "/octopos.rpc.Cluster/GetJobStatus"
	Cluster_ListProcesses_FullMethodName        = "/octopos.rpc.Cluster/ListProcesses"
	Cluster_GetProcess_FullMethodName           = "/octopos.rpc.Cluster/GetProcess"
	Cluster_ListRemoteChildren_FullMethodName   = "/octopos.rpc.Cluster/ListRemoteChildren"
	Cluster_AllocateVFIO_FullMethodName         = "/octopos.rpc.Cluster/AllocateVFIO"
	Cluster_ReleaseVFIO_FullMethodName          = "/octopos.rpc.Cluster/ReleaseVFIO"
	Cluster_GetVFIODevices_FullMethodName       = "/octopos.rpc.Cluster/GetVFIODevices"
	Cluster_CreateSession_FullMethodName        = "/octopos.rpc.Cluster/CreateSession"
	Cluster_DestroySession_FullMethodName       = "/octopos.rpc.Cluster/DestroySession"
	Cluster_ListSessions_FullMethodName         = "/octopos.rpc.Cluster/ListSessions"
	Cluster_ExecStream_FullMethodName           = "/octopos.rpc.Cluster/ExecStream"
	Cluster_RemoteChildExecute_FullMethodName   = "/octopos.rpc.Cluster/RemoteChildExecute"
	Cluster_RemoteChildStream_FullMethodName    = "/octopos.rpc.Cluster/RemoteChildStream"
	Cluster_PipeStream_FullMethodName           = "/octopos.rpc.Cluster/PipeStream"
	Cluster_GetPipeStats_FullMethodName         = "/octopos.rpc.Cluster/GetPipeStats"
	Cluster_RegisterUnixSocket_FullMethodName   = "/octopos.rpc.Cluster/RegisterUnixSocket"
	Cluster_UnregisterUnixSocket_FullMethodName = "/octopos.rpc.Cluster/UnregisterUnixSocket"
	Cluster_ListUnixSockets_FullMethodName      = "/octopos.rpc.Cluster/ListUnixSockets"
	Cluster_UnixSocketStream_FullMethodName     = "/octopos.rpc.Cluster/UnixSocketStream"
)

// ClusterClient is the client API for Cluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Cluster service for inter-node communication
type ClusterClient interface {
	// Node lifecycle
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	GetClusterState(ctx context.Context, in *GetClusterStateRequest, opts ...grpc.CallOption) (*GetClusterStateResponse, error)
	// Job execution
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error)
	Wait(ctx context.Context, in *WaitRequest, opts ...grpc.CallOption) (*WaitResponse, error)
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error)
	// Process tracking
	ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ListProcessesResponse, error)
	GetProcess(ctx context.Context, in *GetProcessRequest, opts ...grpc.CallOption) (*GetProcessResponse, error)
	ListRemoteChildren(ctx context.Context, in *ListRemoteChildrenRequest, opts ...grpc.CallOption) (*ListRemoteChildrenResponse, error)
	// Resource management
	AllocateVFIO(ctx context.Context, in *AllocateVFIORequest, opts ...grpc.CallOption) (*AllocateVFIOResponse, error)
	ReleaseVFIO(ctx context.Context, in *ReleaseVFIORequest, opts ...grpc.CallOption) (*ReleaseVFIOResponse, error)
	GetVFIODevices(ctx context.Context, in *GetVFIODevicesRequest, opts ...grpc.CallOption) (*GetVFIODevicesResponse, error)
	// Session management
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*DestroySessionResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// Streaming for pipes/stdin/stdout
	ExecStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecStreamRequest, ExecStreamResponse], error)
	// Distributed child execution. These entrypoints use the same execution
	// payloads as normal jobs, but require authenticated remote-child metadata.
	RemoteChildExecute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	RemoteChildStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecStreamRequest, ExecStreamResponse], error)
	// Internal pipe graph transport for distributed child endpoints.
	PipeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PipeFrame, PipeFrame], error)
	GetPipeStats(ctx context.Context, in *GetPipeStatsRequest, opts ...grpc.CallOption) (*GetPipeStatsResponse, error)
	// Cluster-wide pathname Unix socket byte-stream broker. V1 only supports
	// filesystem AF_UNIX/SOCK_STREAM sockets under the configured SSI root.
	RegisterUnixSocket(ctx context.Context, in *RegisterUnixSocketRequest, opts ...grpc.CallOption) (*RegisterUnixSocketResponse, error)
	UnregisterUnixSocket(ctx context.Context, in *UnregisterUnixSocketRequest, opts ...grpc.CallOption) (*UnregisterUnixSocketResponse, error)
	ListUnixSockets(ctx context.Context, in *ListUnixSocketsRequest, opts ...grpc.CallOption) (*ListUnixSocketsResponse, error)
	UnixSocketStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UnixSocketFrame, UnixSocketFrame], error)
}

type clusterClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterClient(cc grpc.ClientConnInterface) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, Cluster_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, Cluster_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) GetClusterState(ctx context.Context, in *GetClusterStateRequest, opts ...grpc.CallOption) (*GetClusterStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterStateResponse)
	err := c.cc.Invoke(ctx, Cluster_GetClusterState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, Cluster_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, Cluster_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Wait(ctx context.Context, in *WaitRequest, opts ...grpc.CallOption) (*WaitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitResponse)
	err := c.cc.Invoke(ctx, Cluster_Wait_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobStatusResponse)
	err := c.cc.Invoke(ctx, Cluster_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ListProcessesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProcessesResponse)
	err := c.cc.Invoke(ctx, Cluster_ListProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) GetProcess(ctx context.Context, in *GetProcessRequest, opts ...grpc.CallOption) (*GetProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProcessResponse)
	err := c.cc.Invoke(ctx, Cluster_GetProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) ListRemoteChildren(ctx context.Context, in *ListRemoteChildrenRequest, opts ...grpc.CallOption) (*ListRemoteChildrenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRemoteChildrenResponse)
	err := c.cc.Invoke(ctx, Cluster_ListRemoteChildren_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) AllocateVFIO(ctx context.Context, in *AllocateVFIORequest, opts ...grpc.CallOption) (*AllocateVFIOResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateVFIOResponse)
	err := c.cc.Invoke(ctx, Cluster_AllocateVFIO_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) ReleaseVFIO(ctx context.Context, in *ReleaseVFIORequest, opts ...grpc.CallOption) (*ReleaseVFIOResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseVFIOResponse)
	err := c.cc.Invoke(ctx, Cluster_ReleaseVFIO_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) GetVFIODevices(ctx context.Context, in *GetVFIODevicesRequest, opts ...grpc.CallOption) (*GetVFIODevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVFIODevicesResponse)
	err := c.cc.Invoke(ctx, Cluster_GetVFIODevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, Cluster_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*DestroySessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroySessionResponse)
	err := c.cc.Invoke(ctx, Cluster_DestroySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, Cluster_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) ExecStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecStreamRequest, ExecStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Cluster_ServiceDesc.Streams[0], Cluster_ExecStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecStreamRequest, ExecStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cluster_ExecStreamClient = grpc.BidiStreamingClient[ExecStreamRequest, ExecStreamResponse]

func (c *clusterClient) RemoteChildExecute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, Cluster_RemoteChildExecute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) RemoteChildStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecStreamRequest, ExecStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Cluster_ServiceDesc.Streams[1], Cluster_RemoteChildStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecStreamRequest, ExecStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cluster_RemoteChildStreamClient = grpc.BidiStreamingClient[ExecStreamRequest, ExecStreamResponse]

func (c *clusterClient) PipeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PipeFrame, PipeFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Cluster_ServiceDesc.Streams[2], Cluster_PipeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PipeFrame, PipeFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cluster_PipeStreamClient = grpc.BidiStreamingClient[PipeFrame, PipeFrame]

func (c *clusterClient) GetPipeStats(ctx context.Context, in *GetPipeStatsRequest, opts ...grpc.CallOption) (*GetPipeStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPipeStatsResponse)
	err := c.cc.Invoke(ctx, Cluster_GetPipeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) RegisterUnixSocket(ctx context.Context, in *RegisterUnixSocketRequest, opts ...grpc.CallOption) (*RegisterUnixSocketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterUnixSocketResponse)
	err := c.cc.Invoke(ctx, Cluster_RegisterUnixSocket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) UnregisterUnixSocket(ctx context.Context, in *UnregisterUnixSocketRequest, opts ...grpc.CallOption) (*UnregisterUnixSocketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterUnixSocketResponse)
	err := c.cc.Invoke(ctx, Cluster_UnregisterUnixSocket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) ListUnixSockets(ctx context.Context, in *ListUnixSocketsRequest, opts ...grpc.CallOption) (*ListUnixSocketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUnixSocketsResponse)
	err := c.cc.Invoke(ctx, Cluster_ListUnixSockets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) UnixSocketStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UnixSocketFrame, UnixSocketFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Cluster_ServiceDesc.Streams[3], Cluster_UnixSocketStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UnixSocketFrame, UnixSocketFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cluster_UnixSocketStreamClient = grpc.BidiStreamingClient[UnixSocketFrame, UnixSocketFrame]

// ClusterServer is the server API for Cluster service.
// All implementations must embed UnimplementedClusterServer
// for forward compatibility.
//
// Cluster service for inter-node communication
type ClusterServer interface {
	// Node lifecycle
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	GetClusterState(context.Context, *GetClusterStateRequest) (*GetClusterStateResponse, error)
	// Job execution
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	Signal(context.Context, *SignalRequest) (*SignalResponse, error)
	Wait(context.Context, *WaitRequest) (*WaitResponse, error)
	GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error)
	// Process tracking
	ListProcesses(context.Context, *ListProcessesRequest) (*ListProcessesResponse, error)
	GetProcess(context.Context, *GetProcessRequest) (*GetProcessResponse, error)
	ListRemoteChildren(context.Context, *ListRemoteChildrenRequest) (*ListRemoteChildrenResponse, error)
	// Resource management
	AllocateVFIO(context.Context, *AllocateVFIORequest) (*AllocateVFIOResponse, error)
	ReleaseVFIO(context.Context, *ReleaseVFIORequest) (*ReleaseVFIOResponse, error)
	GetVFIODevices(context.Context, *GetVFIODevicesRequest) (*GetVFIODevicesResponse, error)
	// Session management
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	// Streaming for pipes/stdin/stdout
	ExecStream(grpc.BidiStreamingServer[ExecStreamRequest, ExecStreamResponse]) error
	// Distributed child execution. These entrypoints use the same execution
	// payloads as normal jobs, but require authenticated remote-child metadata.
	RemoteChildExecute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	RemoteChildStream(grpc.BidiStreamingServer[ExecStreamRequest, ExecStreamResponse]) error
	// Internal pipe graph transport for distributed child endpoints.
	PipeStream(grpc.BidiStreamingServer[PipeFrame, PipeFrame]) error
	GetPipeStats(context.Context, *GetPipeStatsRequest) (*GetPipeStatsResponse, error)
	// Cluster-wide pathname Unix socket byte-stream broker. V1 only supports
	// filesystem AF_UNIX/SOCK_STREAM sockets under the configured SSI root.
	RegisterUnixSocket(context.Context, *RegisterUnixSocketRequest) (*RegisterUnixSocketResponse, error)
	UnregisterUnixSocket(context.Context, *UnregisterUnixSocketRequest) (*UnregisterUnixSocketResponse, error)
	ListUnixSockets(context.Context, *ListUnixSocketsRequest) (*ListUnixSocketsResponse, error)
	UnixSocketStream(grpc.BidiStreamingServer[UnixSocketFrame, UnixSocketFrame]) error
	mustEmbedUnimplementedClusterServer()
}

// UnimplementedClusterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterServer struct{}

func (UnimplementedClusterServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedClusterServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedClusterServer) GetClusterState(context.Context, *GetClusterStateRequest) (*GetClusterStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterState not implemented")
}
func (UnimplementedClusterServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedClusterServer) Signal(context.Context, *SignalRequest) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedClusterServer) Wait(context.Context, *WaitRequest) (*WaitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Wait not implemented")
}
func (UnimplementedClusterServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedClusterServer) ListProcesses(context.Context, *ListProcessesRequest) (*ListProcessesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedClusterServer) GetProcess(context.Context, *GetProcessRequest) (*GetProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProcess not implemented")
}
func (UnimplementedClusterServer) ListRemoteChildren(context.Context, *ListRemoteChildrenRequest) (*ListRemoteChildrenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRemoteChildren not implemented")
}
func (UnimplementedClusterServer) AllocateVFIO(context.Context, *AllocateVFIORequest) (*AllocateVFIOResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllocateVFIO not implemented")
}
func (UnimplementedClusterServer) ReleaseVFIO(context.Context, *ReleaseVFIORequest) (*ReleaseVFIOResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseVFIO not implemented")
}
func (UnimplementedClusterServer) GetVFIODevices(context.Context, *GetVFIODevicesRequest) (*GetVFIODevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVFIODevices not implemented")
}
func (UnimplementedClusterServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedClusterServer) DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroySession not implemented")
}
func (UnimplementedClusterServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedClusterServer) ExecStream(grpc.BidiStreamingServer[ExecStreamRequest, ExecStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecStream not implemented")
}
func (UnimplementedClusterServer) RemoteChildExecute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoteChildExecute not implemented")
}
func (UnimplementedClusterServer) RemoteChildStream(grpc.BidiStreamingServer[ExecStreamRequest, ExecStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method RemoteChildStream not implemented")
}
func (UnimplementedClusterServer) PipeStream(grpc.BidiStreamingServer[PipeFrame, PipeFrame]) error {
	return status.Error(codes.Unimplemented, "method PipeStream not implemented")
}
func (UnimplementedClusterServer) GetPipeStats(context.Context, *GetPipeStatsRequest) (*GetPipeStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPipeStats not implemented")
}
func (UnimplementedClusterServer) RegisterUnixSocket(context.Context, *RegisterUnixSocketRequest) (*RegisterUnixSocketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterUnixSocket not implemented")
}
func (UnimplementedClusterServer) UnregisterUnixSocket(context.Context, *UnregisterUnixSocketRequest) (*UnregisterUnixSocketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterUnixSocket not implemented")
}
func (UnimplementedClusterServer) ListUnixSockets(context.Context, *ListUnixSocketsRequest) (*ListUnixSocketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUnixSockets not implemented")
}
func (UnimplementedClusterServer) UnixSocketStream(grpc.BidiStreamingServer[UnixSocketFrame, UnixSocketFrame]) error {
	return status.Error(codes.Unimplemented, "method UnixSocketStream not implemented")
}
func (UnimplementedClusterServer) mustEmbedUnimplementedClusterServer() {}
func (UnimplementedClusterServer) testEmbeddedByValue()                 {}

// UnsafeClusterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterServer will
// result in compilation errors.
type UnsafeClusterServer interface {
	mustEmbedUnimplementedClusterServer()
}

func RegisterClusterServer(s grpc.ServiceRegistrar, srv ClusterServer) {
	// If the following call panics, it indicates UnimplementedClusterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cluster_ServiceDesc, srv)
}

func _Cluster_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_GetClusterState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).GetClusterState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_GetClusterState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).GetClusterState(ctx, req.(*GetClusterStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Signal(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Wait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Wait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_Wait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Wait(ctx, req.(*WaitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_ListProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProcessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).ListProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_ListProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).ListProcesses(ctx, req.(*ListProcessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_GetProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).GetProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_GetProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).GetProcess(ctx, req.(*GetProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_ListRemoteChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRemoteChildrenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).ListRemoteChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_ListRemoteChildren_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).ListRemoteChildren(ctx, req.(*ListRemoteChildrenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_AllocateVFIO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateVFIORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).AllocateVFIO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_AllocateVFIO_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).AllocateVFIO(ctx, req.(*AllocateVFIORequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_ReleaseVFIO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseVFIORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).ReleaseVFIO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_ReleaseVFIO_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).ReleaseVFIO(ctx, req.(*ReleaseVFIORequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_GetVFIODevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVFIODevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).GetVFIODevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_GetVFIODevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).GetVFIODevices(ctx, req.(*GetVFIODevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_DestroySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).DestroySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_DestroySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).DestroySession(ctx, req.(*DestroySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_ExecStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterServer).ExecStream(&grpc.GenericServerStream[ExecStreamRequest, ExecStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cluster_ExecStreamServer = grpc.BidiStreamingServer[ExecStreamRequest, ExecStreamResponse]

func _Cluster_RemoteChildExecute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).RemoteChildExecute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_RemoteChildExecute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).RemoteChildExecute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_RemoteChildStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterServer).RemoteChildStream(&grpc.GenericServerStream[ExecStreamRequest, ExecStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cluster_RemoteChildStreamServer = grpc.BidiStreamingServer[ExecStreamRequest, ExecStreamResponse]

func _Cluster_PipeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterServer).PipeStream(&grpc.GenericServerStream[PipeFrame, PipeFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cluster_PipeStreamServer = grpc.BidiStreamingServer[PipeFrame, PipeFrame]

func _Cluster_GetPipeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).GetPipeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_GetPipeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).GetPipeStats(ctx, req.(*GetPipeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_RegisterUnixSocket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUnixSocketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).RegisterUnixSocket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_RegisterUnixSocket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).RegisterUnixSocket(ctx, req.(*RegisterUnixSocketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_UnregisterUnixSocket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterUnixSocketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).UnregisterUnixSocket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_UnregisterUnixSocket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).UnregisterUnixSocket(ctx, req.(*UnregisterUnixSocketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_ListUnixSockets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUnixSocketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).ListUnixSockets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cluster_ListUnixSockets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).ListUnixSockets(ctx, req.(*ListUnixSocketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_UnixSocketStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterServer).UnixSocketStream(&grpc.GenericServerStream[UnixSocketFrame, UnixSocketFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Cluster_UnixSocketStreamServer = grpc.BidiStreamingServer[UnixSocketFrame, UnixSocketFrame]

// Cluster_ServiceDesc is the grpc.ServiceDesc for Cluster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cluster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "octopos.rpc.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _Cluster_RegisterNode_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Cluster_Heartbeat_Handler,
		},
		{
			MethodName: "GetClusterState",
			Handler:    _Cluster_GetClusterState_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Cluster_Execute_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _Cluster_Signal_Handler,
		},
		{
			MethodName: "Wait",
			Handler:    _Cluster_Wait_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _Cluster_GetJobStatus_Handler,
		},
		{
			MethodName: "ListProcesses",
			Handler:    _Cluster_ListProcesses_Handler,
		},
		{
			MethodName: "GetProcess",
			Handler:    _Cluster_GetProcess_Handler,
		},
		{
			MethodName: "ListRemoteChildren",
			Handler:    _Cluster_ListRemoteChildren_Handler,
		},
		{
			MethodName: "AllocateVFIO",
			Handler:    _Cluster_AllocateVFIO_Handler,
		},
		{
			MethodName: "ReleaseVFIO",
			Handler:    _Cluster_ReleaseVFIO_Handler,
		},
		{
			MethodName: "GetVFIODevices",
			Handler:    _Cluster_GetVFIODevices_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _Cluster_CreateSession_Handler,
		},
		{
			MethodName: "DestroySession",
			Handler:    _Cluster_DestroySession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _Cluster_ListSessions_Handler,
		},
		{
			MethodName: "RemoteChildExecute",
			Handler:    _Cluster_RemoteChildExecute_Handler,
		},
		{
			MethodName: "GetPipeStats",
			Handler:    _Cluster_GetPipeStats_Handler,
		},
		{
			MethodName: "RegisterUnixSocket",
			Handler:    _Cluster_RegisterUnixSocket_Handler,
		},
		{
			MethodName: "UnregisterUnixSocket",
			Handler:    _Cluster_UnregisterUnixSocket_Handler,
		},
		{
			MethodName: "ListUnixSockets",
			Handler:    _Cluster_ListUnixSockets_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecStream",
			Handler:       _Cluster_ExecStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RemoteChildStream",
			Handler:       _Cluster_RemoteChildStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PipeStream",
			Handler:       _Cluster_PipeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UnixSocketStream",
			Handler:       _Cluster_UnixSocketStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/rpc/octopos.proto",
}
